spring.application.name=kitchenApi
server.port=8080


# PostgreSQL Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_order_db
spring.datasource.username=postgres
spring.datasource.password=gms26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always

# Auth Config
auth.admin.password=admin123
auth.kitchen.password=kitchen123
